services:
  node1:
    build: .
    ports:
      - "8001:8000"
    environment:
      NODE_ID: node1
      NODE_HOST: 0.0.0.0
      NODE_PORT: 8000
      NODE_URL: http://node1:8000
      PEERS: http://node1:8000,http://node2:8000,http://node3:8000
      LEADER_ID: node1
      LEADER_URL: http://node1:8000
      API_KEY: devkey
      CLUSTER_HMAC_KEY: devhmac
      ENCRYPTION_KEY: o6bShtNP0D3dYlIuYJzoO3jVXo0b4UR5Iwb5F3m21vk=
      ML_ENABLED: "1"

  node2:
    build: .
    ports:
      - "8002:8000"
    environment:
      NODE_ID: node2
      NODE_HOST: 0.0.0.0
      NODE_PORT: 8000
      NODE_URL: http://node2:8000
      PEERS: http://node1:8000,http://node2:8000,http://node3:8000
      LEADER_ID: node1
      LEADER_URL: http://node1:8000
      API_KEY: devkey
      CLUSTER_HMAC_KEY: devhmac
      ENCRYPTION_KEY: o6bShtNP0D3dYlIuYJzoO3jVXo0b4UR5Iwb5F3m21vk=
      ML_ENABLED: "1"

  node3:
    build: .
    ports:
      - "8003:8000"
    environment:
      NODE_ID: node3
      NODE_HOST: 0.0.0.0
      NODE_PORT: 8000
      NODE_URL: http://node3:8000
      PEERS: http://node1:8000,http://node2:8000,http://node3:8000
      LEADER_ID: node1
      LEADER_URL: http://node1:8000
      API_KEY: devkey
      CLUSTER_HMAC_KEY: devhmac
      ENCRYPTION_KEY: o6bShtNP0D3dYlIuYJzoO3jVXo0b4UR5Iwb5F3m21vk=
      ML_ENABLED: "1"
